### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by godot882** [aryehdesigns/statamic-fetch#1]
Hi @aryehdesigns, thanks for this greatness, just what I was looking for. I only just started with Statamic and don't know much about Addons so please forgive me if I ask something stupid.

Is there any way I can secure these Fetch endpoints? I mean something like, access it only with a token. Can you direct me to right way?

Thanks in advance!

**Comment by aryehdesigns** [comment]
Hey @godot882, that's a very good point. The current version of Fetch doesn't support any kind of restrictions or security via tokens or other means. Perhaps it's something I can look into adding in the future though probably not anytime soon.

You're more than welcome to integrate such a feature yourself and submit a pull request. I'm sure it would benefit others too!

**Comment by aryehdesigns** [comment]
After a second request via Slack for an Authentication option, I went ahead and integrated 2 types:

- API Key
- IP Whitelist

These are configurable via Fetch's Addon Settings page. You can choose to use just one or both options, it's up to you!

Feel free to open another issue if you run into any bugs.

**Comment by bognarl** [comment]
Just a question shouldn't the IP Whitelist function listen to HTTP_X_FORWARDED_FOR instead of REMOTE_ADDR?

**Comment by aryehdesigns** [comment]
I've been reading a lot of different opinions about this topic. [This comment](http://stackoverflow.com/questions/15699101/get-the-client-ip-address-using-php#comment26342911_15699240) from a SO question seems to come back quite often.

IP Whitelisting is never going to be full proof, but REMOTE_ADDR seems to be the safest bet as it is harder to spoof than HTTP_X_FORWARDED_FOR.
